export const LOGGER = {
    APPLICATION: Symbol.for('APPLICATION_LOGGER'),
    DELIVERY: Symbol.for('DELIVERY_LOGGER'),
    DOMAIN: Symbol.for('DOMAIN_LOGGER'),
    INFRASTRUCTURE: Symbol.for('INFRASTRUCTURE_LOGGER'),
    CONTROLLER: Symbol.for('CONTROLLER_LOGGER'),
    USECASE: Symbol.for('USECASE_LOGGER')
}