export const PRODUCT_STEP = {
    FIND_BY_CATEGORY_ID: Symbol.for('FIND_BY_CATEGORY_ID_PRODUCT_STEP'),
    FIND_PRODUCT_DETAILS: Symbol.for('FIND_PRODUCT_DETAILS_PRODUCT_STEP'),
    ADD_PRODUCT_CATEGORY: Symbol.for('ADD_PRODUCT_CATEGORY_PRODUCT_STEP'),
    ADD_PRODUCT_ATTRIBUTES: Symbol.for('ADD_PRODUCT_ATTRIBUTES_PRODUCT_STEP')
}