export const USER_WORKFLOW = {
    CREATE: Symbol.for('CREATE_USER_WORKFLOW'),
    UPDATE: Symbol.for('UPDATE_USER_WORKFLOW'),
    FIND_BY_ID: Symbol.for('FIND_USER_BY_ID_WORKFLOW'),
    PAGINATE: Symbol.for('PAGINATE_USER_WORKFLOW')
}

export const AUTH_WORKFLOW = {
    SIGN_IN: Symbol.for('SIGN_IN_WORKFLOW'),
}

export const CATEGORY_WORKFLOW = {
    CREATE: Symbol.for('CREATE_CATEGORY_WORKFLOW'),
    UPDATE: Symbol.for('UPDATE_CATEGORY_WORKFLOW'),
    FIND_BY_ID: Symbol.for('FIND_CATEGORY_BY_ID_WORKFLOW'),
    PAGINATE: Symbol.for('PAGINATE_CATEGORY_WORKFLOW')
}

export const ATTRIBUTE_VALUE_WORKFLOW = {
    CREATE: Symbol.for('CREATE_ATTRIBUTE_VALUE_WORKFLOW'),
    UPDATE: Symbol.for('UPDATE_ATTRIBUTE_VALUE_WORKFLOW'),
    FIND_BY_ID: Symbol.for('FIND_ATTRIBUTE_VALUE_BY_ID_WORKFLOW'),
    PAGINATE: Symbol.for('PAGINATE_ATTRIBUTE_VALUE_WORKFLOW')
}

export const ATTRIBUTE_WORKFLOW = {
    CREATE: Symbol.for('CREATE_ATTRIBUTE_WORKFLOW'),
    UPDATE: Symbol.for('UPDATE_ATTRIBUTE_WORKFLOW'),
    FIND_BY_ID: Symbol.for('FIND_ATTRIBUTE_BY_ID_WORKFLOW'),
    PAGINATE: Symbol.for('PAGINATE_ATTRIBUTE_WORKFLOW')
}

export const PRODUCT_WORKFLOW = {
    CREATE: Symbol.for('CREATE_PRODUCT_WORKFLOW'),
    UPDATE: Symbol.for('UPDATE_PRODUCT_WORKFLOW'),
    FIND_BY_ID: Symbol.for('FIND_PRODUCT_BY_ID_WORKFLOW'),
    PAGINATE: Symbol.for('PAGINATE_PRODUCT_WORKFLOW'),
    FIND_BY_CATEGORY_ID: Symbol.for('FIND_PRODUCT_BY_CATEGORY_ID_WORKFLOW')
}

export const PRODUCT_SKU_WORKFLOW = {
    CREATE: Symbol.for('CREATE_PRODUCT_SKU_WORKFLOW'),
    UPDATE: Symbol.for('UPDATE_PRODUCT_SKU_WORKFLOW'),
    FIND_BY_ID: Symbol.for('FIND_PRODUCT_SKU_BY_ID_WORKFLOW'),
    PAGINATE: Symbol.for('PAGINATE_PRODUCT_SKU_WORKFLOW'),
    FIND_BY_PRODUCT_ID: Symbol.for('FIND_PRODUCT_SKU_BY_PRODUCT_ID_WORKFLOW'),
}

export const PRODUCT_SKU_ATTRIBUTE_VALUE_WORKFLOW = {
    CREATE: Symbol.for('CREATE_PRODUCT_SKU_ATTRIBUTE_VALUE_WORKFLOW'),
    UPDATE: Symbol.for('UPDATE_PRODUCT_SKU_ATTRIBUTE_VALUE_WORKFLOW'),
    FIND_BY_ID: Symbol.for('FIND_PRODUCT_SKU_ATTRIBUTE_VALUE_BY_ID_WORKFLOW'),
    PAGINATE: Symbol.for('PAGINATE_PRODUCT_SKU_ATTRIBUTE_VALUE_WORKFLOW')
}

export const PRODUCT_ATTRIBUTE_WORKFLOW = {
    CREATE: Symbol.for('CREATE_PRODUCT_ATTRIBUTE_WORKFLOW'),
    UPDATE: Symbol.for('UPDATE_PRODUCT_ATTRIBUTE_WORKFLOW'),
    FIND_BY_ID: Symbol.for('FIND_PRODUCT_ATTRIBUTE_BY_ID_WORKFLOW'),
    PAGINATE: Symbol.for('PAGINATE_PRODUCT_ATTRIBUTE_WORKFLOW')
}

export const PRODUCT_CATEGORY_WORKFLOW = {
    CREATE: Symbol.for('CREATE_PRODUCT_CATEGORY_WORKFLOW'),
    UPDATE: Symbol.for('UPDATE_PRODUCT_CATEGORY_WORKFLOW'),
    FIND_BY_ID: Symbol.for('FIND_PRODUCT_CATEGORY_BY_ID_WORKFLOW'),
    PAGINATE: Symbol.for('PAGINATE_PRODUCT_CATEGORY_WORKFLOW')
}
