export const USER_USECASE = {
    CREATE: Symbol.for('CREATE_USER_USECASE'),
    UPDATE: Symbol.for('UPDATE_USER_USECASE'),
    FIND_BY_ID: Symbol.for('FIND_USER_BY_ID_USECASE'),
    PAGINATE: Symbol.for('PAGINATE_USER_USECASE')
}

export const AUTH_USECASE = {
    SIGN_IN: Symbol.for('SIGN_IN_USECASE'),
}

export const CATEGORY_USECASE = {
    CREATE: Symbol.for('CREATE_CATEGORY_USECASE'),
    UPDATE: Symbol.for('UPDATE_CATEGORY_USECASE'),
    FIND_BY_ID: Symbol.for('FIND_CATEGORY_BY_ID_USECASE'),
    PAGINATE: Symbol.for('PAGINATE_CATEGORY_USECASE')
}

export const ATTRIBUTE_VALUE_USECASE = {
    CREATE: Symbol.for('CREATE_ATTRIBUTE_VALUE_USECASE'),
    UPDATE: Symbol.for('UPDATE_ATTRIBUTE_VALUE_USECASE'),
    FIND_BY_ID: Symbol.for('FIND_ATTRIBUTE_VALUE_BY_ID_USECASE'),
    PAGINATE: Symbol.for('PAGINATE_ATTRIBUTE_VALUE_USECASE')
}

export const ATTRIBUTE_USECASE = {
    CREATE: Symbol.for('CREATE_ATTRIBUTE_USECASE'),
    UPDATE: Symbol.for('UPDATE_ATTRIBUTE_USECASE'),
    FIND_BY_ID: Symbol.for('FIND_ATTRIBUTE_BY_ID_USECASE'),
    PAGINATE: Symbol.for('PAGINATE_ATTRIBUTE_USECASE')
}

export const PRODUCT_USECASE = {
    CREATE: Symbol.for('CREATE_PRODUCT_USECASE'),
    UPDATE: Symbol.for('UPDATE_PRODUCT_USECASE'),
    FIND_BY_ID: Symbol.for('FIND_PRODUCT_BY_ID_USECASE'),
    PAGINATE: Symbol.for('PAGINATE_PRODUCT_USECASE'),
    FIND_BY_CATEGORY_ID: Symbol.for('FIND_PRODUCT_BY_CATEGORY_ID_USECASE')
}

export const PRODUCT_SKU_USECASE = {
    CREATE: Symbol.for('CREATE_PRODUCT_SKU_USECASE'),
    UPDATE: Symbol.for('UPDATE_PRODUCT_SKU_USECASE'),
    FIND_BY_ID: Symbol.for('FIND_PRODUCT_SKU_BY_ID_USECASE'),
    PAGINATE: Symbol.for('PAGINATE_PRODUCT_SKU_USECASE'),
    FIND_BY_PRODUCT_ID: Symbol.for('FIND_PRODUCT_SKU_BY_PRODUCT_ID_USECASE'),
}

export const PRODUCT_SKU_ATTRIBUTE_VALUE_USECASE = {
    CREATE: Symbol.for('CREATE_PRODUCT_SKU_ATTRIBUTE_VALUE_USECASE'),
    UPDATE: Symbol.for('UPDATE_PRODUCT_SKU_ATTRIBUTE_VALUE_USECASE'),
    FIND_BY_ID: Symbol.for('FIND_PRODUCT_SKU_ATTRIBUTE_VALUE_BY_ID_USECASE'),
    PAGINATE: Symbol.for('PAGINATE_PRODUCT_SKU_ATTRIBUTE_VALUE_USECASE')
}

export const PRODUCT_ATTRIBUTE_USECASE = {
    CREATE: Symbol.for('CREATE_PRODUCT_ATTRIBUTE_USECASE'),
    UPDATE: Symbol.for('UPDATE_PRODUCT_ATTRIBUTE_USECASE'),
    FIND_BY_ID: Symbol.for('FIND_PRODUCT_ATTRIBUTE_BY_ID_USECASE'),
    PAGINATE: Symbol.for('PAGINATE_PRODUCT_ATTRIBUTE_USECASE')
}

export const PRODUCT_CATEGORY_USECASE = {
    CREATE: Symbol.for('CREATE_PRODUCT_CATEGORY_USECASE'),
    UPDATE: Symbol.for('UPDATE_PRODUCT_CATEGORY_USECASE'),
    FIND_BY_ID: Symbol.for('FIND_PRODUCT_CATEGORY_BY_ID_USECASE'),
    PAGINATE: Symbol.for('PAGINATE_PRODUCT_CATEGORY_USECASE')
}
